---

- name: remove compose dir
  shell: rm -rf /compose
  ignore_errors: True

- name: remove gluster volume                
  shell: rm -rf	/gluster_volume
  ignore_errors: True

- name: remove codebase                
  shell: rm -rf	/atm-codebase
  ignore_errors: True


- name: create directory for compose files
  file: path=/compose state=directory mode=0755

- name: copy rancher compose files
  copy: src=rancher-compose.yml dest=/compose/ mode=u+rwx

- name: copy docker compose files
  copy: src=docker-compose.yml dest=/compose/ mode=u+rwx




- name: create API key
  uri:
      url="http://172.27.59.136:8080/v1/projects/1a5/apikeys"
      return_content=yes
      method=POST
      status_code=200
      HEADER_Content-Type="application/json"
  register: project_id
  ignore_errors: True


- debug: var={{ project_id.json.publicValue }}

- debug: var={{ project_id.json.secretValue }}

- debug: var={{ project_id.json.id }}




- name: create APP Stack
  shell: cd /compose; rancher-compose --url {{ RANCHER_URL }} --access-key {{ project_id.json.publicValue }} --secret-key {{ project_id.json.secretValue }} -p ALM-TASK-MANAGER create


- name: start pxc service
  shell: cd /compose; rancher-compose --url {{ RANCHER_URL }} --access-key {{ project_id.json.publicValue }} --secret-key {{ project_id.json.secretValue }} -p ALM-TASK-MANAGER start pxc



- name: start gluster service
  shell: cd /compose; rancher-compose --url {{ RANCHER_URL }} --access-key {{ project_id.json.publicValue }} --secret-key {{ project_id.json.secretValue }} -p ALM-TASK-MANAGER start gluster


- pause: seconds=60


- name: start app service
  shell: cd /compose; rancher-compose --url {{ RANCHER_URL }} --access-key {{ project_id.json.publicValue }} --secret-key {{ project_id.json.secretValue }} -p ALM-TASK-MANAGER start atm-app
  

- name: start lb service
  shell: cd /compose; rancher-compose --url {{ RANCHER_URL }} --access-key {{ project_id.json.publicValue }} --secret-key {{ project_id.json.secretValue }} -p ALM-TASK-MANAGER start lb
 
- pause: seconds=60





- name: Dactivate API key
  uri:
      url="http://172.27.59.136:8080/v1/projects/1a5/apikeys/{{ project_id.json.id }}?action=deactivate"
      return_content=yes
      method=POST
      status_code=200
      HEADER_Content-Type="application/json"
  ignore_errors: True

- name: Delete API key
  uri:
      url="http://172.27.59.136:8080/v1/projects/1a5/apikeys/{{ project_id.json.id }}"
      return_content=yes
      method=DELETE
      status_code=200
      HEADER_Content-Type="application/json"
  ignore_errors: True
